version: 2
jobs:
  build:
    machine: true
    steps:
    - run:
        name: download hasura cli
        command: |
          curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
    - run:
        name: apply hasura migration
        command: |
          hasura init --directory hasura --endpoint https://react-auth0-hasura.herokuapp.com

          cd hasura
          hasura migrate create "init" --from-server
          hasura migrate apply --admin-secret 'valleyforge' --up 1