version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
    - run:
        name: install bash
        command: |
          apk update
          apk upgrade
          apk add bash
    - run:
        name: download hasura cli
        command: |
          curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
    - run:
        name: apply hasura migration
        command: |
          hasura init --directory hasura --endpoint https://hasura-with-circleci.herokuapp.com

          cd hasura
          hasura migrate create "init" --from-server
          hasura migrate apply