version: 2
jobs:
  apply_migrations:
    - run:
      name: apply migrations
      working_directory: ./hasura
      command: |
      curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
      hasura migrate apply --admin-secret valleyforge